language: smalltalk
sudo: false

matrix:
  include:
    - smalltalk: Squeak-trunk
      smalltalk_config: .default.ston
      os: linux
    - smalltalk: Squeak-trunk
      env: BUILD_NAME=Squeak-5.3
      smalltalk_config: .tests.ston
      os: linux
    - smalltalk: Squeak-5.2
      smalltalk_config: .default.ston
      os: linux
    - smalltalk: Squeak-5.2
      env: BUILD_NAME=Squeak-5.2
      smalltalk_config: .tests.ston
      os: linux

    - smalltalk: Pharo-alpha
      smalltalk_config: .default.ston
      os: linux
    - smalltalk: Pharo-alpha
      env: BUILD_NAME=Pharo-7.0
      smalltalk_config: .tests.ston
      os: linux
    - smalltalk: Pharo-alpha
      smalltalk_config: .corewithextras.ston
      os: linux
    - smalltalk: Pharo-alpha
      smalltalk_config: .developmentgroup.ston
      os: linux

    - smalltalk: Pharo64-alpha
      smalltalk_config: .default.ston
      os: linux
    - smalltalk: Pharo64-alpha
      env: BUILD_NAME=Pharo-7.0-64
      smalltalk_config: .tests.ston
      os: linux
    - smalltalk: Pharo64-alpha
      smalltalk_config: .corewithextras.ston
      os: linux
    - smalltalk: Pharo64-alpha
      smalltalk_config: .developmentgroup.ston
      os: linux
