language: smalltalk
sudo: false

matrix:
  allow_failures:
    - smalltalk: Squeak-trunk
    - smalltalk: Pharo-alpha
    - smalltalk: Pharo64-alpha
  include:
    - smalltalk: Squeak-trunk
      smalltalk_config: .default.ston
      os: linux
    - smalltalk: Squeak-trunk
      smalltalk_config: .tests.ston
      os: linux

    - smalltalk: Pharo-alpha
      smalltalk_config: default.ston
      os: linux
    - smalltalk: Pharo-alpha
      smalltalk_config: tests.ston
      os: linux
    - smalltalk: Pharo-alpha
      smalltalk_config: corewithextras.ston
      os: linux
    - smalltalk: Pharo-alpha
      smalltalk_config: developmentgroup.ston
      os: linux

    - smalltalk: Pharo64-alpha
      smalltalk_config: default.ston
      os: linux
    - smalltalk: Pharo64-alpha
      smalltalk_config: tests.ston
      os: linux
    - smalltalk: Pharo64-alpha
      smalltalk_config: corewithextras.ston
      os: linux
    - smalltalk: Pharo64-alpha
      smalltalk_config: developmentgroup.ston
      os: linux
