language: smalltalk
sudo: false

# Squeak 5.0 can't load Traits due to a bug in the class format definition.
# This issue has been fixed in trunk

matrix:
  include:
    # Squeak-trunk-> stable
    - smalltalk: Squeak-trunk
      smalltalk_config: .stable-default.ston
      os: linux
    - smalltalk: Squeak-trunk
      smalltalk_config: .stable-tests.ston
      os: linux
    # - smalltalk: Squeak-trunk
    #   smalltalk_config: .stable-corewithextras.ston
    #   os: linux
    # Squeak-5.1 -> stable
    - smalltalk: Squeak-5.1
      smalltalk_config: .stable-default.ston
      os: linux
    - smalltalk: Squeak-5.1
      smalltalk_config: .stable-tests.ston
      os: linux
    # - smalltalk: Squeak-5.1
    #   smalltalk_config: .stable-corewithextras.ston
    #   os: linux
    # Squeak-4.6 -> stable
    - smalltalk: Squeak-4.6
      smalltalk_config: .stable-default.ston
      os: linux
    - smalltalk: Squeak-4.6
      smalltalk_config: .stable-tests.ston
      os: linux
    # - smalltalk: Squeak-4.6
    #   smalltalk_config: .stable-corewithextras.ston
    #   os: linux
    # Squeak-4.5
    - smalltalk: Squeak-4.5
      smalltalk_config: .stable-default.ston
      os: linux
    - smalltalk: Squeak-4.5
      smalltalk_config: .stable-tests.ston
      os: linux
    # - smalltalk: Squeak-4.5
    #   smalltalk_config: .stable-corewithextras.ston
    #   os: linux
    # Pharo-alpha -> bleedingEdge
    - smalltalk: Pharo-alpha
      smalltalk_config: .bleedingedge-default.ston
      os: linux
    - smalltalk: Pharo-alpha
      smalltalk_config: .bleedingedge-tests.ston
      os: linux
    - smalltalk: Pharo-alpha
      smalltalk_config: .bleedingedge-corewithextras.ston
      os: linux
    - smalltalk: Pharo-alpha
      smalltalk_config: .bleedingedge-developmentgroup.ston
      os: linux
    # Pharo-6.0 -> stable
    - smalltalk: Pharo-6.0
      smalltalk_config: .stable-default.ston
      os: linux
    - smalltalk: Pharo-6.0
      smalltalk_config: .stable-tests.ston
      os: linux
    - smalltalk: Pharo-6.0
      smalltalk_config: .stable-corewithextras.ston
      os: linux
    # Pharo-5.0 -> stable
    - smalltalk: Pharo-5.0
      smalltalk_config: .stable-default.ston
      os: linux
    - smalltalk: Pharo-5.0
      smalltalk_config: .stable-tests.ston
      os: linux
    - smalltalk: Pharo-5.0
      smalltalk_config: .stable-corewithextras.ston
      os: linux
    # Pharo-4.0 -> stable
    - smalltalk: Pharo-4.0
      smalltalk_config: .stable-default.ston
      os: linux
    - smalltalk: Pharo-4.0
      smalltalk_config: .stable-tests.ston
      os: linux
    - smalltalk: Pharo-4.0
      smalltalk_config: .stable-corewithextras.ston
      os: linux
